# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu2204"
    config.vm.hostname = "lfmdata"
    config.vm.synced_folder "./../..", "/vagrant", 
      type: "nfs",
      nfs_version: ENV['NFS_VERSION'], # ! Note ! You need this env var on your system
      nfs_udp: false

    config.vm.network "forwarded_port", guest: 5000, host: 5000 
    config.vm.provision :shell, path: "./../provision.sh"  
    config.vm.provider :libvirt do |v|
        v.default_prefix = "lfmdata"
    end
end 